services:
  solace-api:
    container_name: solace-api
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      LOG_FORMAT: dev
      LOG_DIR: /logs
      ORIGIN: "*"
      PORT: 3000
      SECRET_KEY: secretKey
      CREDENTIALS: true
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44*^i33xs7G2V^z%
      POSTGRES_HOST: pg-solace
      POSTGRES_PORT: 5432
      POSTGRES_DB: public
      REDIS_HOST: redis-solace
      OTEL_METRICS_EXPORTER: None
    volumes:
      - ./:/solace
      - /solace/node_modules
    restart: unless-stopped
    networks:
      - backend-solace
    depends_on:
      - pg-solace
      - redis-solace  # Ensure server depends on Redis

  pg-solace:
    container_name: pg-solace
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44*^i33xs7G2V^z%
      POSTGRES_DB: public
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - backend-solace

  redis-solace:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
      - redis_data:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD="+Uly7Ezx/VkukgCzRpiicVF2JGtZnK5eoaeIQuDADyIY7lEwnL1FsKK5ptjhC/53"
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    container_name: redis-solace
    networks:
      - backend-solace


networks:
  backend-solace:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
