services:
  proxy-solace:
    image: nginx:alpine
    container_name: proxy-solace
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - backend-solace

  solace-api:
    container_name: solace-api
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44*^i33xs7G2V^z%
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: public
      REDIS_HOST: redis  # Add Redis host environment variable
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend-solace
    depends_on:
      - pg-solace
      - redis-solace  # Ensure server depends on Redis

  pg-solace:
    container_name: pg-solace
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44*^i33xs7G2V^z%
      POSTGRES_DB: public
    volumes:
      # - ./postgresdata:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - backend-solace

  redis-solace:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/root/redis
    environment:
      - REDIS_PASSWORD="+Uly7Ezx/VkukgCzRpiicVF2JGtZnK5eoaeIQuDADyIY7lEwnL1FsKK5ptjhC/53"
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    container_name: redis-solace
    networks:
      - backend-solace


networks:
  backend-solace:
    driver: bridge

volumes:
  data:
    driver: local
  redisdata:
    driver: local
